config/routes.rb
Rails.application.routes.draw do
  get 'searches/index'

  get 'welcome/index'

  devise_for :admins
  devise_for :users,  :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :products do
    resources :reviews
    member do
      put 'like', to: 'products#upvote'
      put 'unlike', to: 'products#downvote'
    end
  end

  resources :stores

  get 'styles/new'
  post 'styles/create'
  get 'styles/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root 'welcome#index'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :style
  belongs_to :user

  has_and_belongs_to_many :choices
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  include PgSearch
  multisearchable :against => :name

  has_and_belongs_to_many :products
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :style

  has_and_belongs_to_many :answers

  # validates_presence_of :answer

  mount_uploader :image, AvatarUploader
end

app/models/product.rb
class Product < ApplicationRecord

  include PgSearch
  pg_search_scope :search_by_tags, :against => [:tags, :name],
                  using: {
                      tsearch: {
                          any_word: true
                      }
                  }

   multisearchable :against => [:name, :description, :price, :tags]

  acts_as_votable

  belongs_to :store
  has_many :reviews
  has_and_belongs_to_many :categories

  validates_presence_of :name, :price, :description, :image

  mount_uploader :image, AvatarUploader

 scope :price, -> (price) { where price: price }
 scope :productname, -> (name) { where("name like ?", "#{name}%")}
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :styles
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
end

app/models/store.rb
class Store < ApplicationRecord
	include PgSearch
	multisearchable :against => :name

	has_many :products
	validates_presence_of :name, :website, :logo

	mount_uploader :logo, AvatarUploader
end

app/models/style.rb
class Style < ApplicationRecord
  belongs_to :quiz
  has_many :answers
  has_many :choices
  validates_presence_of :question
end

app/models/user.rb
class User < ApplicationRecord

  has_many :answers

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  acts_as_voter

end

app/controllers/users.rb
class UsersController < ApplicationController
  layout 'formlayout'
  before_action :set_user, only: [:show, :edit, :update, :destroy]


      # GET /users/:id.:format
      def show
        # authorize! :read, @user
      end

      # GET /users/:id/edit
  def edit
    # authorize! :update, @user
  end

      # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

      # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

      # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    accessible = [ :name, :email ] # extend with your own params
    accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
    params.require(:user).permit(accessible)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width">
    <title>Fablook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= render 'partials/header' %><br>

    <% flash.each do |key, message| %>
      <div class="alert alert-<%= key %>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>

    <%= render 'partials/footer' %>
  </body>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/layouts/formlayout.html.erb
<!DOCTYPE html>
<html>
<<<<<<< HEAD
  <head>
    <title>Fablook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>

  	<% flash.each do |key, message| %>
  		<div class="alert alert-<%= key %>">
        <%= message %>
      </div>
  	<% end %>
    <%= yield %>
  </body>
</html>

app/views/partials/_footer.html.erb
<!-- footer -->
<div class="footer">
	<div class="container-fluid extend">
		<div class="row">
			<div class="col-sm-3 col-offset-2 text-center">
				<p>My Account</p>
				<ul class="list-unstyled">
					<li><a href="fablook.com">Sale</a></li>
					<li><a href="fablook.com">My Style</a></li>
					<li><a href="fablook.com">Invite Friends</a></li>
					<li><a href="fablook.com">Follow Trends</a></li>
				</ul>
			</div>
			<div class="col-sm-3 text-center">
				<p>About us</p>
				<ul class="list-unstyled">
					<li><a href="fablook.com">Blog</a></li>
					<li><a href="fablook.com">Our Brand</a></li>
					<li><a href="fablook.com">Terms of use</a></li>
					<li><a href="fablook.com">Privacy and policy</a></li>
				</ul>
			</div>

			<div class="col-sm-3 text-center newsright">
				<p>Follow Fablook</p>
				<ul class="list-inline">
              		<li><a href="https://twitter.com/truetestar" target="_blank"> <i class="fa fa-twitter social"></i></a></li>
              		<li><a href="https://facebook.com/truetestar" target="_blank"> <i class="fa fa-facebook social"></i></a></li>
              		<li><a href="https://twitter.com/truetestar" target="_blank"> <i class="fa fa-envelope social"></i></a></li>
              		<li><a href="https://twitter.com/truetestar" target="_blank"> <i class="fa fa-youtube-square social"></i></a></li>
            	</ul>	
            				
			</div>
			<div class="col-sm-3 col-offset-2 text-center">
			<p>Sign up to our newsletter for updates</p>
				<form>
					<input type="email" class="form-control" value="" name="" placeholder="email">
					<br>
					<button class="btn btn-warning">
					Subscribe
					</button>
				</form>				
			</div>
			
		</div>	
		<hr>
		<h6 class="copy-right">© 2017 Fablook. All rights reserved.</h6>		
	</div>
</div>
<!-- //footer -->

</body>
</html>

app/views/partials/_header.html.erb
<!-- banner -->
<script>
(function(e,t){var r=e.rakam||{};var n=t.createElement("script");n.type="text/javascript";
n.async=true;n.src="https://d2f7xo8n6nlhxf.cloudfront.net/rakam.beta.min.js";
n.onload=function(){e.rakam.runQueuedFunctions()};var a=t.getElementsByTagName("script")[0];
a.parentNode.insertBefore(n,a);function s(e,t){e[t]=function(){this._q.push([t].concat(Array.prototype.slice.call(arguments,0)));
return this}}var i=function(){this._q=[];return this};var o=["set","setOnce","increment","unset"];
for(var c=0;c<o.length;c++){s(i.prototype,o[c])}r.User=i;r._q=[];var u=["init","logEvent","logInlinedEvent","setUserId","getUserId","getDeviceId","setSuperProperties","setOptOut","setVersionName","setDomain","setUserProperties","setDeviceId","onload","onEvent","getTimeOnPreviousPage","getTimeOnPage","startTimer","isReturningUser"];
for(var m=0;m<u.length;m++){s(r,u[m])}e.rakam=r})(window,document);

rakam.init("hpokin8jnmope3hige8hb3ljbj7pf99qo6rgfqmshm3gpjh7meqad9ai93dckel6", "user_id", { 
apiEndpoint:"nestmetricai.herokuapp.com/", 
includeUtm: true, 
trackClicks: true, 
trackForms: true, 
includeReferrer: true,
saveEvents: true,
batchEvents: true,
eventUploadThreshold: 30,
eventUploadPeriodMillis: 30000
}, function() {
var e = document.documentElement, g = document.getElementsByTagName('body')[0],
x = window.innerWidth || e.clientWidth || g.clientWidth,
y = window.innerHeight|| e.clientHeight|| g.clientHeight;

rakam.logEvent("pageview", {url: window.location.pathname, time_on_page: rakam.getTimeOnPreviousPage(), returning_session: rakam.isReturningUser(), color_depth: window.screen.colorDepth, viewport: x + ' × ' + y, title: document.title});
});
rakam.startTimer(true);

rakam.setSuperProperties({platform: 'Web', _ip: true, _user_agent:true, _referrer:document.referrer, resolution: window.screen.width+" × "+window.screen.height}, true);
</script>
<div class="container-fluid">
	<nav class="navbar navbar-fixed-top navbar-default nav-color ">
	<p>test</p>
				<div class="navbar-header">
				  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-collapse" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				  </button>
				</div>
				<div class="collapse navbar-collapse" id="nav-collapse">
				  <ul class="nav link-color menu__list pull-left">
					<li class="menu__item"> <%= link_to 'Fablook', welcome_index_path, class: "" %> <span class="sr-only">(current)</span></li>
            		<li class=" menu__item"><%= link_to 'Stores', stores_path, class: "" %></li>
            		<li class="dropdown menu__item">
						<a href="" class="dropdown-toggle " data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sale <span class="caret"></span></a>
							<ul class="dropdown-menu multi-column columns-3">
								<div class="row">
									<div class="col-sm-3 multi-gd-img">
										<ul class="multi-column-dropdown">
											<li><%= link_to 'Clothing', products_path + "?category_id=5" %></li>
                      <li><%= link_to 'Shoes', products_path + "?category_id=6"  %></li>
                      <li><%= link_to 'Beauty', products_path + "?category_id=11" %></li>
                      <li><%= link_to 'Accessories', products_path + "?category_id=9" %></li>
										</ul>
									</div>
								</div>
							</ul>
					</li>
					<li class="dropdown menu__item">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Fabs <span class="caret"></span></a>
							<ul class="dropdown-menu multi-column columns-3">
								<div class="row">

									<div class="col-sm-3 multi-gd-img">
										<ul class="multi-column-dropdown">
                      <li><%= link_to 'Clothing', products_path + "?category_id=5" %></li>
                      <li><%= link_to 'Shoes', products_path + "?category_id=6"  %></li>
                      <li><%= link_to 'Beauty', products_path + "?category_id=11" %></li>
                      <li><%= link_to 'Accessories', products_path + "?category_id=9" %></li>
										</ul>

									</div>

									<div class="clearfix"></div>

								</div>
							</ul>
					</li>
					
				  </ul>
				<ul class="nav link-color menu__list pull-right">
				  <div class="col-md-12">
            <li>
                <!-- Searchbar -->
                <%= form_tag searches_index_path, :method => 'get', id: 'search-form' do %>
                  <p>
                    <%= text_field_tag :search, params[:search], placeholder: 'Search Style' , class: 'form-control'  %>
                   </p>
                <% end %>
            </li>
          </div>
        </ul>
        <ul>
        	<li>
						<ul class="nav link-color menu__list pull-right">
				  	<li class="menu__item"><a class="" href="https://medium.com/@TessieWaithira">Blog</a></li>
				  	<li class=" menu__item"><%= link_to 'My Style', styles_new_path, class: "" %></li>
              		<% if user_signed_in? %>
                  		<li class="dropdown">
                    		<a class="dropdown-toggle" data-toggle="dropdown" href="#">
                      		<%= current_user.name %>
                      		<span class="caret"></span>
                    		</a>
                    		<ul class="dropdown-menu" role="menu">
                      			<li><%= link_to 'Profile', edit_user_registration_path %></li>
                      			<li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                    		</ul>
                  		</li>
              		<% else %>
                  		<li class="dropdown">
                  			<ul class="dropdown-menu" role="menu">
                  				<li menu__item><%= link_to 'Log In', new_user_session_path %></li>
                  				<li menu__item><%= link_to 'Sign Up', new_user_registration_path %></li>
                  			</ul>
                  		</li>
              		<% end %>
              		</ul>
					</li>
        </ul>

				</div>


	</nav>
</div>
<hr>

app/views/partials/_review.html.erb
<h2>Review:</h2>
<%= simple_form_for([@product, @product.reviews.build]) do |f| %>
    <p>
      <%= f.input :name %>
    </p>
    <p>
      <%= f.input :comment %>
    </p>
    <p>
      <%= f.button :submit, class: "btn-primary" %>
    </p>
<% end %>