config/routes.rb
Rails.application.routes.draw do
  get 'searches/index'

  get 'welcome/index'

  devise_for :admins
  devise_for :users,  :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :products do
    resources :reviews
    member do
      put 'like', to: 'products#upvote'
      put 'unlike', to: 'products#downvote'
    end
  end

  resources :stores

  get 'styles/new'
  post 'styles/create'
  get 'styles/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root 'welcome#index'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :style
  belongs_to :user

  has_and_belongs_to_many :choices
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  include PgSearch
  multisearchable :against => :name

  has_and_belongs_to_many :products
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :style

  has_and_belongs_to_many :answers

  # validates_presence_of :answer

  mount_uploader :image, AvatarUploader
end

app/models/product.rb
class Product < ApplicationRecord

  include PgSearch
  pg_search_scope :search_by_tags, :against => [:tags, :name],
                  using: {
                      tsearch: {
                          any_word: true
                      }
                  }

   multisearchable :against => [:name, :description, :price, :tags]

  acts_as_votable

  belongs_to :store
  has_many :reviews
  has_and_belongs_to_many :categories

  validates_presence_of :name, :price, :description, :image

  mount_uploader :image, AvatarUploader

 scope :price, -> (price) { where price: price }
 scope :productname, -> (name) { where("name like ?", "#{name}%")}
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :styles
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
end

app/models/store.rb
class Store < ApplicationRecord
	include PgSearch
	multisearchable :against => :name

	has_many :products
	validates_presence_of :name, :website, :logo

	mount_uploader :logo, AvatarUploader
end

app/models/style.rb
class Style < ApplicationRecord
  belongs_to :quiz
  has_many :answers
  has_many :choices
  validates_presence_of :question
end

app/models/user.rb
class User < ApplicationRecord

  has_many :answers

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  acts_as_voter

end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  def index
    @choices = Choice.all
  end
  def show
    @choice = Choice.find(params[:id])
  end
  def new
    @choice = Choice.new
  end
  def create
    @style = Choice.find(params[style_id])
    @choice = @style.choices.create(choice_params)
		if @choice.save
			redirect_to @choice
		else
			render "new"
		end
  end

  def update
      @style = Choice.find(params[style_id])
    @choice.update(choice_params)

    redirect_to @style
  end

  private

  def choice_params
    params.require(:choice).permit(:answer)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
	def index
			@stores = Store.all
	end

	def show
		@store = Store.find(params[:id])
	end

	def new
		@store = Store.new
	end

	def create
		@store = Store.new(store_params)
		if @store.save
			redirect_to @store
		else
			render 'new'
		end
	end

	def edit
		@store = Store.find(params[:id])
	end

	def update
		@store = Store.find(params[:id])

		@store.update(store_params)

		redirect_to @store
	end

	def destroy
		@store = Store.find(params[:id])
		@store.destroy
		redirect_to store_path
	end

	private

	def store_params
		params.require(:store).permit(:name, :website, :location)
	end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :authenticate_user!
  layout 'formlayout'


  def new
    @quiz = Quiz.find(3)
  end

  def create
    quiz = params[:quiz]

    @answers = []
    quiz.each do |style_id, style|
      answer = Answer.create(user: current_user,
                             style_id: style_id,
                             choices: Choice.find(style[:choice_ids])
      )

      @answers.push answer
    end

    redirect_to products_path
  end
end

app/controllers/users.rb
class UsersController < ApplicationController
  layout 'formlayout'
  before_action :set_user, only: [:show, :edit, :update, :destroy]


      # GET /users/:id.:format
      def show
        # authorize! :read, @user
      end

      # GET /users/:id/edit
  def edit
    # authorize! :update, @user
  end

      # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

      # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

      # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    accessible = [ :name, :email ] # extend with your own params
    accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
    params.require(:user).permit(accessible)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/stores/index.html.erb
<h3>Features stores</h3>
<hr>
<div class="container">
	<% @stores.each do |store| %>
	<div class="row">
		<div class="col-md-6 col-md-offset-4">
			<div class="card" style="width: 30rem;">
  			 <%= image_tag store.logo_url(:thumbnail)%>
  			<div class="card-block">
   			<h4 class="card-title"><%= store.name %></h4>
    		<p class="card-text"><%= store.website %></p>
    		  <a href="<%= store.website %>" class="btn btn-primary">Visit</a>
  			</div>
			</div>
		</div>
	</div>
	<hr>
	<% end %>
</div>

app/views/styles/new.html.erb
<div class="container-fluid question-style">
  <div class="top-content">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 text">
          <div class="description">
            <div class="row">
              <div class="col-md-4">
                <p>Take the quiz to find the perfect shapes and styles for you</p>
              </div>
              <div class="col-md-4">
                <p>Tell us what like and dislike to keep your edits up to date</p>
              </div>
              <div class="col-md-4">
                <p>Check your wardrobe and inbox for edits tailored to you</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12 form-box">
          <%= form_tag styles_create_path, method: 'post' do %>
              <hr>

              <% @quiz.styles.each_with_index do |question, index| %>
              <fieldset>
                        <div class="form-group">
                          <p><%= "#{index + 1}. #{question.question}" %></p><br>
                          <div class="row">
                            <% question.choices.in_groups_of(6, false) do |group| %>
                              <div class="row">
                                <% group.each do |choice|%>
                                <div class="col-md-2">
                                  <input type="checkbox"
                                         name="<%= "quiz[#{question.id}[choice_ids]][]" %>"
                                         value="<%= choice.id %>"
                                         id="<%= choice.id %>">
                                  <label for="<%= choice.id %>">
                                    <%= image_tag choice.image_url(:thumbnail), class:'img-responsive img-rounded form-image' %>
                                  </label>
                                  <br>
                                  <br>
                                </div>
                              <% end %>
                              </div>
                            <% end %>
                          </div>
                        </div>
                  </fieldset>
                  <!--<div class="f1-buttons">-->
                    <!--<button type="button" class="btn btn-next">Next</button>-->
                  <!--</div>-->
              <% end %>
              <button type="submit" class="btn btn-info pull-right" >Create Style</button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/styles/show.html.erb
<p>
  <strong>Question:</strong>
  <%= @style.question %>
</p>

<% @style.choices.in_groups_of(3, false) do |group| %>
  <div class = "row">
    <% group.each do |choice| %>
      <div class="col-md-4">
          <%= choice.answer %><br>
          <%= image_tag choice.image_url(:thumbnail), :width => 400, :height => 400 %>
          <div class="row gap">
          <button class="btn btn-primary">Yes</button>
          <button class="btn btn-danger">No</button>
          </div>
      </div>
    <% end %>
  </div>

<% end %>