config/routes.rb
Rails.application.routes.draw do
  get 'searches/index'

  get 'welcome/index'

  devise_for :admins
  devise_for :users,  :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :products do
    resources :reviews
    member do
      put 'like', to: 'products#upvote'
      put 'unlike', to: 'products#downvote'
    end
  end

  resources :stores

  get 'styles/new'
  post 'styles/create'
  get 'styles/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root 'welcome#index'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :style
  belongs_to :user

  has_and_belongs_to_many :choices
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  include PgSearch
  multisearchable :against => :name

  has_and_belongs_to_many :products
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :style

  has_and_belongs_to_many :answers

  # validates_presence_of :answer

  mount_uploader :image, AvatarUploader
end

app/models/product.rb
class Product < ApplicationRecord

  include PgSearch
  pg_search_scope :search_by_tags, :against => [:tags, :name],
                  using: {
                      tsearch: {
                          any_word: true
                      }
                  }

   multisearchable :against => [:name, :description, :price, :tags]

  acts_as_votable

  belongs_to :store
  has_many :reviews
  has_and_belongs_to_many :categories

  validates_presence_of :name, :price, :description, :image

  mount_uploader :image, AvatarUploader

 scope :price, -> (price) { where price: price }
 scope :productname, -> (name) { where("name like ?", "#{name}%")}
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :styles
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
end

app/models/store.rb
class Store < ApplicationRecord
	include PgSearch
	multisearchable :against => :name

	has_many :products
	validates_presence_of :name, :website, :logo

	mount_uploader :logo, AvatarUploader
end

app/models/style.rb
class Style < ApplicationRecord
  belongs_to :quiz
  has_many :answers
  has_many :choices
  validates_presence_of :question
end

app/models/user.rb
class User < ApplicationRecord

  has_many :answers

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  acts_as_voter

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :set_product, only: [:show, :upvote, :downvote]

	def index
		@tags = ''

		if current_user
			current_user.answers.each do |answer|
				answer.choices.each do |choice|
					@tags = [@tags, choice.tags].join('')
				end
			end
			@products = Product.search_by_tags(@tags)
			# if params[:category_id]
			# 	@products = Category.find_by(id: params[:category_id]).products
			# end
		else
			@products = Product.order("created_at DESC")

			if params[:category_id]
				@products = Category.find_by(id: params[:category_id]).products
			end

		end

		@pg_search_documents = PgSearch.multisearch(params[:search])
		# if params[:search]
		# 	@products = PgSearch.multisearch(params[:search])
		# elsif params[:category_id]
		# 	@products = Category.find_by(id: params[:category_id]).products
		# else
		# 	@products = Product.order("created_at DESC")
		# end
	end

	def search
		@products = Product.search_tags(params[:query])
	end

	def show
		@product = Product.find(params[:id])
	end

	def create
		@product = Product.new(product_params)

		if @product.save
			redirect_to @product
		else
			render "new"
		end

	end

	def upvote
		authenticate_user!
		@product.upvote_by current_user
		redirect_to product_path
	end

	def downvote
		authenticate_user!
		@product.downvote_by current_user
		redirect_to product_path
	end

	private

	def set_product
		@product = Product.find(params[:id])
	end

	def product_params
		params.require(:product).permit(:name, :price, :description, :image, :category)
	end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
	def index
			@stores = Store.all
	end

	def show
		@store = Store.find(params[:id])
	end

	def new
		@store = Store.new
	end

	def create
		@store = Store.new(store_params)
		if @store.save
			redirect_to @store
		else
			render 'new'
		end
	end

	def edit
		@store = Store.find(params[:id])
	end

	def update
		@store = Store.find(params[:id])

		@store.update(store_params)

		redirect_to @store
	end

	def destroy
		@store = Store.find(params[:id])
		@store.destroy
		redirect_to store_path
	end

	private

	def store_params
		params.require(:store).permit(:name, :website, :location)
	end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :authenticate_user!
  layout 'formlayout'


  def new
    @quiz = Quiz.find(3)
  end

  def create
    quiz = params[:quiz]

    @answers = []
    quiz.each do |style_id, style|
      answer = Answer.create(user: current_user,
                             style_id: style_id,
                             choices: Choice.find(style[:choice_ids])
      )

      @answers.push answer
    end

    redirect_to products_path
  end
end

app/controllers/users.rb
class UsersController < ApplicationController
  layout 'formlayout'
  before_action :set_user, only: [:show, :edit, :update, :destroy]


      # GET /users/:id.:format
      def show
        # authorize! :read, @user
      end

      # GET /users/:id/edit
  def edit
    # authorize! :update, @user
  end

      # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

      # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

      # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    accessible = [ :name, :email ] # extend with your own params
    accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
    params.require(:user).permit(accessible)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/products/index.html.erb
<div class="product"></div>
<div class="container-fluid products">
  <%if current_user%>
   <p>Matching Products</p>
  <% else %>
      <p>Products</p>
  <% end%>
  <hr>
  <div class="row">
    <div class="col-md-3">
    <p>Category</p>
        <ul class="list-unstyled">
          <li><%= link_to 'Clothing', products_path + "?category_id=5" %></li>
          <li><%= link_to 'Shoes', products_path + "?category_id=6"  %></li>
          <li><%= link_to 'Beauty', products_path + "?category_id=11" %></li>
          <li><%= link_to 'Accessories', products_path + "?category_id=9" %></li>
        </ul>
    <hr>     
    <p>Price</p>
    <select>
      <option value="">16-20</option>
      <option value="">21-25</option>
      <option value="">Above 30</option>
      <option value="" selected>$20</option>
    </select> 
    <hr>
    <p>Sorted by</p>
    <select>
      <option value="">16-20</option>
      <option value="">21-25</option>
      <option value="">Above 30</option>
      <option value="" selected>Store</option>
    </select>
    <hr>
                   
    </div>
    <div class="col-md-9">
       <% @products.in_groups_of(4, false) do |group| %>
          <div class="row">
             <% group.each do |product| %>

                  <div class="col-md-3">
                    <div class="card demo-card" style="width: 20rem; ">
                      <%= image_tag product.image_url(:thumbnail), class: "card-img-top img-size" %>
                      <div class="card-block">
                       <p><%= product.name %> </p>
                       <p class="item_price">$<%= product.price %></p>
                       <%= link_to 'View Details', product_path(product) , class: "btn btn-default" %>
                      </div>
                    </div>
                  </div>

            <% end %>
          </div>
      <% end %>

    </div>

  </div>
</div>

app/views/products/show.html.erb
<div class="product"></div>
<div class="container">
  <div class="row product">
    <div class="col-md-4">
      <%= image_tag @product.image_url(:thumbnail), :width => 400, :height => 400, :class => "img-responsive" %>          
    </div>
    <div class="col-md-8">
      <div class="row">
      <p>Product overview</p>
      <hr>
      <div class="info-product-price">
        <h4><%= @product.name %></h4>
        <span class="item_price">$<%= @product.price %></span>
      </div>
      <hr>
      <p>Share</p>
      <%= social_share_button_tag(@product.name, :allow_sites => %w(twitter facebook)) %>
      <hr>
      <div>
      <p>Like|Dislike</p>
      <button class="btn btn-large">
       <%= link_to like_product_path(@product), method: :put do %>
        <i class="fa fa-heart" aria-hidden="true">
          <%= @product.get_upvotes.size %>          
        </i>
        <% end %>
        <%= link_to unlike_product_path(@product), method: :put do %>
        <i class="fa fa-thumbs-down" aria-hidden="true">
          <span class=“badge”><%= @product.get_downvotes.size %></span>          
        </i>
        <% end %>
      </button>

      </div>
      <hr>
        <a target="_blank" href="<%= @product.source %>" class="btn btn-warning">BUY</a>
      </div>
      <hr>
      <div class="row">
        <div class="col-md-6">
          <p>Product Brief Description</p>
            <p> <%= @product.description %> </p>          
        </div>
        <div class="col-md-6 verticalline">
        <h4>Add a review</h4>
                  <% @product.reviews.each do |review| %>
                      <p>
                        <strong>name:</strong>
                        <%= review.name %>
                      </p>

                      <p>
                        <%= review.comment %>
                      </p>
                  <% end %>
                  <%= render 'partials/review' %>          
        </div>        
      </div>         
    </div>
  </div>  
</div>
</div>
<hr>